### ISSUE TITLE
`test` folder included at the root of the python folder

### ISSUE THREAD

**Issue by hadim** [conda-forge/botorch-feedstock#9]
The `test` folder is included during the installation, creating warning messages when it conflicts with other packages:

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/noarch::gpytorch-1.5.1-pyhd8ed1ab_0, conda-forge/noarch::botorch-0.2.2-py_0
  path: 'lib/python3.9/site-packages/test/optim/__pycache__/__init__.cpython-39.pyc'
```

**Comment by ngam** [comment]
We should delete the test folder. I can try to do that soon. I will want to hear from others first just in case. I will start a pr to force-delete and see how that goes...

**Comment by ngam** [comment]
see #10
